a = input ('Digite algo: ')
print('O tipo primitivo deste valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfábetico? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em Maiúsculas? ', a.isupper())
print('Está em minúsculas? ', a.islower())